### ISSUE TITLE
Unexpected response 404

### ISSUE THREAD

**Issue by weilinzung** [vblagoje/auto-pr#2]
Hello, we are getting below error

```
Traceback (most recent call last):
  File "/main.py", line 496, in <module>
    service_response = invoke_service_pipe.run(
  File "/opt/venv/lib/python3.10/site-packages/haystack/core/pipeline/pipeline.py", line 788, in run
    res = comp.run(**last_inputs[name])
  File "/opt/venv/lib/python3.10/site-packages/haystack/components/connectors/openapi_service.py", line 73, in run
    service_response = self._invoke_method(openapi_service, method_invocation_descriptor)
  File "/opt/venv/lib/python3.10/site-packages/haystack/components/connectors/openapi_service.py", line 217, in _invoke_method
    return method_to_call(**method_call_params)
  File "/opt/venv/lib/python3.10/site-packages/openapi3/openapi.py", line 256, in __call__
    return self.operation(self.base_url, *args, security=self.security, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/openapi3/paths.py", line 357, in request
    raise UnexpectedResponseError(result, self)
openapi3.errors.UnexpectedResponseError: Unexpected response 404 from compare_branches (expected one of 200, no default is defined)
```

---

```
name: Generate PR Description
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]

jobs:
  main:
    name: PR Description
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR Description
        uses: vblagoje/pr-auto@v1
        id: pr_auto
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          generation_model: gpt-4o-mini
          user_prompt: test generating
```

**Comment by vblagoje** [comment]
Thanks for reporting - I'll fix this over the weekend!

**Comment by vblagoje** [comment]
Hey @weilinzung try it out now. I've released new version of Docker [image](https://hub.docker.com/r/vblagoje/openapi-rag-service/) and updated the project [itself](https://github.com/vblagoje/openapi-rag-service) to use the latest Haystack release. 

Give it a go, it should work now. Do let me know.

**Comment by weilinzung** [comment]
@vblagoje after re-running the action, now we are getting another the 404 error. 

![IMG_0666](https://github.com/user-attachments/assets/0050392f-0a19-41d8-b0a7-f62db22493ae)

**Comment by vblagoje** [comment]
Ok, thanks for reporting back @weilinzung , let me fix that. 

I ran the pr-auto in my test project via https://github.com/vblagoje/workflow-playground/pull/186 and it worked fine. Perhaps you can compare your workflow with the [workflow](https://github.com/vblagoje/workflow-playground/blob/main/.github/workflows/test-update-pr.yml) in the test project. 

Let me know how they differ and we'll figure it out.

**Comment by weilinzung** [comment]
@vblagoje It seems it is a Github API issue, the issue example is what I have, nothing special. The only difference is our repo is private?

**Comment by weilinzung** [comment]
Also, what permissions of the GitHub action token should be granted?

**Comment by vblagoje** [comment]
Have a look at https://github.com/vblagoje/pr-auto/blob/main/action.yml - these are all relevant github action parameters - you definitely need to setup your CI token to access your internal repo.

**Comment by weilinzung** [comment]
I have the github token there for sure.

**Comment by vblagoje** [comment]
Any progress on this @weilinzung ? Is anyone else having some issues with the new build of https://github.com/vblagoje/openapi-rag-service that runs both https://github.com/vblagoje/pr-auto and https://github.com/vblagoje/reno-auto ? cc @lgavinho @brunowego @hematoyogi @blakenorthone @amkillam

**Comment by weilinzung** [comment]
it should be the token issue, all good for now. Thanks
